# Generated by Django 4.2.16 on 2024-09-24 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("skill", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoryTrace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.IntegerField()),
                ("updated_at", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "rarity",
                    models.IntegerField(choices=[(4, "R"), (5, "SR"), (6, "SSR")]),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("vitality", "体质"),
                            ("defence", "防御"),
                            ("attack", "攻击"),
                            ("mastery", "专精"),
                            ("terminal", "终端"),
                        ],
                        max_length=50,
                    ),
                ),
                ("artist", models.CharField(default="", max_length=50)),
                ("implemented_at", models.IntegerField(blank=True, null=True)),
                ("acquisitions", models.JSONField(default=list)),
                ("description", models.TextField(default="")),
                ("illustration_1", models.TextField(default="")),
                ("illustration_2", models.TextField(default="")),
            ],
            options={
                "db_table": "inner_mark_info",
            },
        ),
        migrations.CreateModel(
            name="NexusEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.IntegerField()),
                ("updated_at", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(default="")),
                ("level_max_addition", models.TextField(default="")),
                (
                    "memory_trace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nexus_effects",
                        to="memory_trace.memorytrace",
                    ),
                ),
            ],
            options={
                "db_table": "memory_trace_nexus_effect",
            },
        ),
        migrations.CreateModel(
            name="NexusStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.IntegerField()),
                ("updated_at", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("unlock_level", models.IntegerField(default=-1)),
                (
                    "memory_trace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nexus_stats",
                        to="memory_trace.memorytrace",
                    ),
                ),
            ],
            options={
                "db_table": "memory_trace_nexus_stat",
            },
        ),
        migrations.CreateModel(
            name="NexusStatLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.IntegerField()),
                ("updated_at", models.IntegerField(blank=True, null=True)),
                ("level", models.IntegerField()),
                ("value", models.FloatField()),
                (
                    "nexus_stat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="memory_trace.nexusstat",
                    ),
                ),
            ],
            options={
                "db_table": "memory_trace_nexus_stat_level",
            },
        ),
        migrations.CreateModel(
            name="NexusEffectLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.IntegerField()),
                ("updated_at", models.IntegerField(blank=True, null=True)),
                ("level", models.IntegerField()),
                ("values", models.JSONField()),
                (
                    "nexus_effect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="memory_trace.nexuseffect",
                    ),
                ),
            ],
            options={
                "db_table": "memory_trace_nexus_effect_level",
            },
        ),
        migrations.CreateModel(
            name="MemoryTraceEngravingSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.IntegerField()),
                ("updated_at", models.IntegerField(blank=True, null=True)),
                (
                    "engraving_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skill.engravingskill",
                    ),
                ),
                (
                    "memory_trace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="memory_trace.memorytrace",
                    ),
                ),
            ],
            options={
                "db_table": "memory_trace_engraving_skill_relationship",
            },
        ),
        migrations.AddField(
            model_name="memorytrace",
            name="engraving_skills",
            field=models.ManyToManyField(
                through="memory_trace.MemoryTraceEngravingSkill",
                to="skill.engravingskill",
            ),
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.IntegerField()),
                ("updated_at", models.IntegerField(blank=True, null=True)),
                ("sort_number", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=50)),
                ("type", models.CharField(default="", max_length=50)),
                ("condition", models.CharField(default="", max_length=50)),
                ("description", models.TextField(default="")),
                ("detail", models.TextField(default="")),
                (
                    "memory_trace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="memory_trace.memorytrace",
                    ),
                ),
            ],
            options={
                "db_table": "memory_trace_content",
            },
        ),
        migrations.CreateModel(
            name="BasicStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.IntegerField()),
                ("updated_at", models.IntegerField(blank=True, null=True)),
                ("level", models.IntegerField()),
                ("vitality", models.IntegerField()),
                ("defence", models.IntegerField()),
                ("attack", models.IntegerField()),
                ("mastery", models.IntegerField()),
                ("terminal", models.IntegerField()),
                (
                    "memory_trace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basic_stats",
                        to="memory_trace.memorytrace",
                    ),
                ),
            ],
            options={
                "db_table": "memory_trace_basic_stat",
            },
        ),
        migrations.CreateModel(
            name="Awaking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.IntegerField()),
                ("updated_at", models.IntegerField(blank=True, null=True)),
                ("phase_number", models.IntegerField()),
                ("choice_number", models.IntegerField()),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("vitality", "体质"),
                            ("defence", "防御"),
                            ("attack", "攻击"),
                            ("mastery", "专精"),
                            ("terminal", "终端"),
                            ("skill_point", "技能点"),
                        ],
                        max_length=50,
                    ),
                ),
                ("values", models.JSONField(default=list)),
                (
                    "memory_trace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awakings",
                        to="memory_trace.memorytrace",
                    ),
                ),
            ],
            options={
                "db_table": "memory_trace_awaking",
            },
        ),
        migrations.AddConstraint(
            model_name="nexusstatlevel",
            constraint=models.UniqueConstraint(
                fields=("nexus_stat", "level"), name="unique_nexus_stat_level"
            ),
        ),
        migrations.AddConstraint(
            model_name="memorytraceengravingskill",
            constraint=models.UniqueConstraint(
                fields=("memory_trace", "engraving_skill"),
                name="unique_memory_trace_engraving_skill",
            ),
        ),
        migrations.AddConstraint(
            model_name="basicstat",
            constraint=models.UniqueConstraint(
                fields=("memory_trace", "level"), name="unique_memory_trace_basic_stat"
            ),
        ),
        migrations.AddConstraint(
            model_name="awaking",
            constraint=models.UniqueConstraint(
                fields=("memory_trace", "phase_number", "choice_number"),
                name="unique_awaking",
            ),
        ),
    ]
