# Generated by Django 5.1.2 on 2024-10-22 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("en_name", models.CharField(default="", max_length=50)),
                ("jp_name", models.CharField(default="", max_length=50)),
                ("cn_cv", models.CharField(default="", max_length=50)),
                ("jp_cv", models.CharField(default="", max_length=50)),
                ("profession", models.CharField(max_length=50)),
                ("element", models.CharField(max_length=50)),
                (
                    "rarity",
                    models.IntegerField(choices=[(4, "R"), (5, "SR"), (6, "SSR")]),
                ),
                ("tags", models.JSONField(default=list)),
                ("prototype", models.CharField(max_length=50)),
                ("implemented_at", models.DateField(blank=True, null=True)),
                ("acquisitions", models.JSONField(default=list)),
                ("expressions", models.JSONField(default=list)),
            ],
            options={
                "db_table": "character_info",
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_number", models.IntegerField(unique=True)),
                ("description", models.TextField(default="")),
            ],
            options={
                "db_table": "character_collection",
            },
        ),
        migrations.CreateModel(
            name="Combat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attack_tags", models.JSONField(default=list)),
                ("attack_range", models.CharField(max_length=50)),
                ("attack_range_value", models.IntegerField()),
                ("attack_speed", models.FloatField()),
                ("attack_description", models.TextField()),
                ("critical_rate", models.IntegerField()),
                ("basic_damage_reduction", models.IntegerField()),
                ("reposition_distance", models.IntegerField()),
                ("reposition_cooldown", models.IntegerField()),
                ("mastery_on_healing", models.IntegerField()),
                ("mastery_on_damage_bonus", models.IntegerField()),
                ("mastery_on_block", models.IntegerField()),
                ("character_enhancement", models.TextField(default="")),
            ],
            options={
                "db_table": "character_combat",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("content", models.TextField(default="")),
            ],
            options={
                "db_table": "character_document",
            },
        ),
        migrations.CreateModel(
            name="DomSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(default="")),
            ],
            options={
                "db_table": "character_dom_skill",
            },
        ),
        migrations.CreateModel(
            name="EngravingStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("level", models.IntegerField()),
                ("vitality", models.IntegerField()),
                ("defence", models.IntegerField()),
                ("attack", models.IntegerField()),
                ("mastery", models.IntegerField()),
                ("terminal", models.IntegerField()),
            ],
            options={
                "db_table": "character_engraving_stat",
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(default="")),
                ("detail", models.TextField(default="")),
            ],
            options={
                "db_table": "character_equipment",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gender", models.CharField(max_length=50)),
                ("height", models.IntegerField(default=-1)),
                ("birthday", models.CharField(default="", max_length=50)),
                ("document_name", models.CharField(default="", max_length=50)),
                ("birth_world", models.CharField(default="", max_length=50)),
                ("alias_name", models.CharField(default="", max_length=50)),
                ("faction", models.CharField(default="", max_length=50)),
                ("teleported_from", models.CharField(default="", max_length=100)),
                ("birthplace", models.CharField(default="", max_length=100)),
                ("address", models.TextField(default="")),
                ("brief_report", models.TextField(default="")),
            ],
            options={
                "db_table": "character_report",
            },
        ),
        migrations.CreateModel(
            name="Seed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("init_compatibility", models.CharField(default="", max_length=250)),
                (
                    "cell_synchronisation_rate",
                    models.CharField(default="", max_length=250),
                ),
                ("inspection_agency", models.CharField(default="", max_length=50)),
                ("comment", models.TextField(default="")),
            ],
            options={
                "db_table": "character_seed",
            },
        ),
        migrations.CreateModel(
            name="SeedStableCompatibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("compatibility_number", models.IntegerField()),
                ("detail", models.TextField(default="")),
            ],
            options={
                "db_table": "character_seed_stable_compatibility",
            },
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phase", models.IntegerField()),
            ],
            options={
                "db_table": "character_training",
            },
        ),
        migrations.CreateModel(
            name="TrainingProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_number", models.IntegerField()),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("vitality", "体质"),
                            ("defence", "防御"),
                            ("attack", "攻击"),
                            ("mastery", "专精"),
                            ("terminal", "终端"),
                            ("attack_speed", "攻击速度"),
                            ("healing", "治愈力"),
                            ("block", "格挡强度"),
                            ("basic_damage_reduction", "减伤"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                ("value", models.IntegerField()),
            ],
            options={
                "db_table": "character_training_program",
            },
        ),
        migrations.CreateModel(
            name="Trait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "character_trait",
            },
        ),
        migrations.CreateModel(
            name="TraitLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("level", models.IntegerField()),
                ("description", models.TextField(default="")),
            ],
            options={
                "db_table": "character_trait_level",
            },
        ),
        migrations.CreateModel(
            name="BasicStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("level", models.IntegerField(unique=True)),
                ("vitality", models.IntegerField()),
                ("attack", models.IntegerField()),
                ("mastery", models.IntegerField()),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basic_stats",
                        to="character.character",
                    ),
                ),
            ],
            options={
                "db_table": "character_stat",
            },
        ),
        migrations.CreateModel(
            name="CharacterEngravingSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.character",
                    ),
                ),
            ],
            options={
                "db_table": "character_engraving_skill_relationship",
            },
        ),
    ]
