# Generated by Django 4.2.16 on 2024-09-20 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("character", "0001_initial"),
        ("skill", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterpassiveskill",
            name="passive_skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="skill.passiveskill"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="passive_skills",
            field=models.ManyToManyField(
                through="character.CharacterPassiveSkill", to="skill.passiveskill"
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="character",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="character.character"
            ),
        ),
        migrations.AddConstraint(
            model_name="trainingprogram",
            constraint=models.UniqueConstraint(
                fields=("training", "name"), name="unique_character_training_program"
            ),
        ),
        migrations.AddConstraint(
            model_name="training",
            constraint=models.UniqueConstraint(
                fields=("character", "phase"), name="unique_character_training_phase"
            ),
        ),
        migrations.AddConstraint(
            model_name="stat",
            constraint=models.UniqueConstraint(
                fields=("character", "level"), name="unique_character_stat"
            ),
        ),
        migrations.AddConstraint(
            model_name="seedstablecompatibility",
            constraint=models.UniqueConstraint(
                fields=("seed", "compatibility_number"),
                name="unique_seed_stable_compatibility",
            ),
        ),
        migrations.AddConstraint(
            model_name="seed",
            constraint=models.UniqueConstraint(
                fields=("character", "name"), name="unique_character_seed"
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                fields=("character",), name="unique_character_report"
            ),
        ),
        migrations.AddConstraint(
            model_name="etchingstat",
            constraint=models.UniqueConstraint(
                fields=("character", "level"), name="unique_character_etching_stat"
            ),
        ),
        migrations.AddConstraint(
            model_name="equipment",
            constraint=models.UniqueConstraint(
                fields=("character", "name"), name="unique_character_equipment"
            ),
        ),
        migrations.AddConstraint(
            model_name="domskill",
            constraint=models.UniqueConstraint(
                fields=("character", "name"), name="unique_character_dom_skill"
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                fields=("character", "name"), name="unique_character_document"
            ),
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(
                fields=("character", "collection_number"),
                name="unique_character_collection",
            ),
        ),
        migrations.AddConstraint(
            model_name="characterpassiveskill",
            constraint=models.UniqueConstraint(
                fields=("character", "passive_skill"),
                name="unique_character_passive_skill",
            ),
        ),
    ]
