# Generated by Django 5.1.2 on 2024-10-22 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("character", "0001_initial"),
        ("skill", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterengravingskill",
            name="engraving_skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="skill.engravingskill"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="engraving_skills",
            field=models.ManyToManyField(
                through="character.CharacterEngravingSkill", to="skill.engravingskill"
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections",
                to="character.character",
            ),
        ),
        migrations.AddField(
            model_name="combat",
            name="character",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="character.character"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="character.character",
            ),
        ),
        migrations.AddField(
            model_name="domskill",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dom_skills",
                to="character.character",
            ),
        ),
        migrations.AddField(
            model_name="engravingstat",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="engraving_stats",
                to="character.character",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="character",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="character.character"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="character",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="character.character"
            ),
        ),
        migrations.AddField(
            model_name="seed",
            name="character",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="character.character"
            ),
        ),
        migrations.AddField(
            model_name="seedstablecompatibility",
            name="seed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stable_compatibilities",
                to="character.seed",
            ),
        ),
        migrations.AddField(
            model_name="training",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trainings",
                to="character.character",
            ),
        ),
        migrations.AddField(
            model_name="trainingprogram",
            name="training",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_programs",
                to="character.training",
            ),
        ),
        migrations.AddField(
            model_name="trait",
            name="character",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="character.character"
            ),
        ),
        migrations.AddField(
            model_name="traitlevel",
            name="trait",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trait_levels",
                to="character.trait",
            ),
        ),
        migrations.AddConstraint(
            model_name="basicstat",
            constraint=models.UniqueConstraint(
                fields=("character", "level"), name="unique_character_basic_stat"
            ),
        ),
        migrations.AddConstraint(
            model_name="characterengravingskill",
            constraint=models.UniqueConstraint(
                fields=("character", "engraving_skill"),
                name="unique_character_engraving_skill",
            ),
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(
                fields=("character", "sort_number"), name="unique_character_collection"
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                fields=("character", "name"), name="unique_character_document"
            ),
        ),
        migrations.AddConstraint(
            model_name="domskill",
            constraint=models.UniqueConstraint(
                fields=("character", "name"), name="unique_character_dom_skill"
            ),
        ),
        migrations.AddConstraint(
            model_name="engravingstat",
            constraint=models.UniqueConstraint(
                fields=("character", "level"), name="unique_character_engraving_stat"
            ),
        ),
        migrations.AddConstraint(
            model_name="seed",
            constraint=models.UniqueConstraint(
                fields=("character", "name"), name="unique_character_seed"
            ),
        ),
        migrations.AddConstraint(
            model_name="seedstablecompatibility",
            constraint=models.UniqueConstraint(
                fields=("seed", "compatibility_number"),
                name="unique_seed_stable_compatibility",
            ),
        ),
        migrations.AddConstraint(
            model_name="training",
            constraint=models.UniqueConstraint(
                fields=("character", "phase"), name="unique_character_training_phase"
            ),
        ),
        migrations.AddConstraint(
            model_name="trainingprogram",
            constraint=models.UniqueConstraint(
                fields=("training", "sort_number"),
                name="unique_character_training_program",
            ),
        ),
        migrations.AddConstraint(
            model_name="trait",
            constraint=models.UniqueConstraint(
                fields=("character", "name"), name="unique_character_trait"
            ),
        ),
        migrations.AddConstraint(
            model_name="traitlevel",
            constraint=models.UniqueConstraint(
                fields=("trait", "level"), name="unique_trait_level"
            ),
        ),
    ]
