# Generated by Django 4.2.16 on 2024-09-24 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("character", "0001_initial"),
        ("skill", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterengravingskill",
            name="engraving_skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="skill.engravingskill"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="engraving_skills",
            field=models.ManyToManyField(
                through="character.CharacterEngravingSkill", to="skill.engravingskill"
            ),
        ),
        migrations.AddField(
            model_name="basicstat",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basic_stats",
                to="character.character",
            ),
        ),
        migrations.AddConstraint(
            model_name="trainingprogram",
            constraint=models.UniqueConstraint(
                fields=("training", "name"), name="unique_character_training_program"
            ),
        ),
        migrations.AddConstraint(
            model_name="training",
            constraint=models.UniqueConstraint(
                fields=("character", "phase"), name="unique_character_training_phase"
            ),
        ),
        migrations.AddConstraint(
            model_name="seedstablecompatibility",
            constraint=models.UniqueConstraint(
                fields=("seed", "compatibility_number"),
                name="unique_seed_stable_compatibility",
            ),
        ),
        migrations.AddConstraint(
            model_name="seed",
            constraint=models.UniqueConstraint(
                fields=("character", "name"), name="unique_character_seed"
            ),
        ),
        migrations.AddConstraint(
            model_name="engravingstat",
            constraint=models.UniqueConstraint(
                fields=("character", "level"), name="unique_character_engraving_stat"
            ),
        ),
        migrations.AddConstraint(
            model_name="domskill",
            constraint=models.UniqueConstraint(
                fields=("character", "name"), name="unique_character_dom_skill"
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                fields=("character", "name"), name="unique_character_document"
            ),
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(
                fields=("character", "sort_number"), name="unique_character_collection"
            ),
        ),
        migrations.AddConstraint(
            model_name="characterengravingskill",
            constraint=models.UniqueConstraint(
                fields=("character", "engraving_skill"),
                name="unique_character_engraving_skill",
            ),
        ),
        migrations.AddConstraint(
            model_name="basicstat",
            constraint=models.UniqueConstraint(
                fields=("character", "level"), name="unique_character_basic_stat"
            ),
        ),
    ]
