# Generated by Django 5.1.2 on 2024-10-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicstat",
            name="level",
            field=models.IntegerField(),
        ),
    ]
