# Generated by Django 5.1.2 on 2024-10-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0003_alter_basicstat_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="sort_number",
            field=models.IntegerField(),
        ),
    ]
