# Generated by Django 4.2.16 on 2024-09-20 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("character", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("type", models.CharField(max_length=50)),
                ("tag", models.JSONField(default=list)),
                ("cooldown_type", models.CharField(default="", max_length=50)),
                ("cooldown", models.IntegerField(default=0)),
                ("cast_limitation", models.IntegerField(default=-1)),
                ("description", models.TextField(default="")),
                ("is_seed", models.BooleanField(default=False)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_skills",
                        to="character.character",
                    ),
                ),
            ],
            options={
                "db_table": "skill_active",
            },
        ),
        migrations.CreateModel(
            name="PassiveSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("motivation", "激励"),
                            ("core", "核心"),
                            ("regular", "常规"),
                        ],
                        max_length=50,
                    ),
                ),
                ("rarity", models.IntegerField()),
                ("profession", models.JSONField(default=list)),
                ("profession_type", models.JSONField(default=list)),
                ("tag", models.JSONField(default=list)),
                ("description", models.TextField(default="")),
                ("icon", models.CharField(default="", max_length=100)),
                ("source", models.CharField(default="", max_length=100)),
                ("point_requirement", models.JSONField(default=list)),
                ("element", models.JSONField(default=list)),
                ("skill_attribute", models.CharField(default="", max_length=100)),
                ("enemy_type", models.JSONField(default=list)),
                ("activation_mode", models.JSONField(default=list)),
                ("damage_increase", models.JSONField(default=list)),
                ("damage_reduction", models.IntegerField()),
                ("target_debuff", models.JSONField(default=list)),
                ("stat_increase", models.JSONField(default=list)),
                ("special_mechanism", models.JSONField(default=list)),
            ],
            options={
                "db_table": "skill_passive",
            },
        ),
        migrations.CreateModel(
            name="ActiveSkillLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("level", models.IntegerField()),
                ("values", models.JSONField(default=dict)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="skill.activeskill",
                    ),
                ),
            ],
            options={
                "db_table": "skill_active_level",
            },
        ),
        migrations.AddConstraint(
            model_name="activeskilllevel",
            constraint=models.UniqueConstraint(
                fields=("skill", "level"), name="unique_skill_level"
            ),
        ),
        migrations.AddConstraint(
            model_name="activeskill",
            constraint=models.UniqueConstraint(
                fields=("character", "name"), name="unique_character_active_skill"
            ),
        ),
    ]
