# Generated by Django 4.2.16 on 2024-09-24 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("character", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CombatSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("type", models.CharField(max_length=50)),
                ("tags", models.JSONField(default=list)),
                ("cooldown_type", models.CharField(default="", max_length=50)),
                ("cooldown", models.IntegerField(default=0)),
                ("availability", models.IntegerField(default=-1)),
                ("description", models.TextField(default="")),
                ("cast_condition", models.TextField(default="")),
                ("cast_duration", models.IntegerField(default=-1)),
                ("is_seed", models.BooleanField(default=False)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combat_skills",
                        to="character.character",
                    ),
                ),
            ],
            options={
                "db_table": "combat_skill",
            },
        ),
        migrations.CreateModel(
            name="EngravingSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[("awaking", "唤醒"), ("nexus", "漫巡")], max_length=50
                    ),
                ),
                (
                    "rarity",
                    models.IntegerField(choices=[(4, "R"), (5, "SR"), (6, "SSR")]),
                ),
                ("professions", models.JSONField(default=list)),
                ("profession_types", models.JSONField(default=list)),
                ("tags", models.JSONField(default=list)),
                ("description", models.TextField(default="")),
                ("icon", models.CharField(default="", max_length=100)),
                ("source", models.CharField(default="", max_length=100)),
                ("point_requirement", models.JSONField(default=list)),
                ("elements", models.JSONField(default=list)),
                ("skill_stats", models.CharField(default="", max_length=100)),
                ("enemy_types", models.JSONField(default=list)),
                ("activation_modes", models.JSONField(default=list)),
                ("damage_increases", models.JSONField(default=list)),
                ("damage_reduction", models.IntegerField()),
                ("target_debuffs", models.JSONField(default=list)),
                ("stat_increases", models.JSONField(default=list)),
                ("special_mechanism", models.JSONField(default=list)),
                ("is_motivation", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "engraving_skill",
            },
        ),
        migrations.CreateModel(
            name="CombatSkillLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("level", models.IntegerField()),
                ("values", models.JSONField(default=dict)),
                (
                    "combat_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="skill.combatskill",
                    ),
                ),
            ],
            options={
                "db_table": "combat_skill_level",
            },
        ),
        migrations.AddConstraint(
            model_name="combatskilllevel",
            constraint=models.UniqueConstraint(
                fields=("combat_skill", "level"), name="unique_combat_skill_level"
            ),
        ),
        migrations.AddConstraint(
            model_name="combatskill",
            constraint=models.UniqueConstraint(
                fields=("character", "name"), name="unique_character_combat_skill"
            ),
        ),
    ]
