# Generated by Django 5.1.2 on 2024-10-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="engravingskill",
            name="is_motivation",
        ),
        migrations.AlterField(
            model_name="engravingskill",
            name="type",
            field=models.CharField(
                choices=[("inspire", "激励"), ("core", "核心"), ("regular", "常规")],
                max_length=50,
                null=True,
            ),
        ),
    ]
