# Generated by Django 5.1.2 on 2024-10-22 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0002_remove_engravingskill_is_motivation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="engravingskill",
            old_name="stat_increases",
            new_name="stats_increases",
        ),
    ]
