# Generated by Django 4.2.16 on 2024-09-19 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("skill", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrossingStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("unlock_level", models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name="InnerMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "rarity",
                    models.IntegerField(choices=[(4, "R"), (5, "SR"), (6, "SSR")]),
                ),
                (
                    "stat_type",
                    models.CharField(
                        choices=[
                            ("health", "体质"),
                            ("defence", "防御"),
                            ("attack", "攻击"),
                            ("mastery", "专精"),
                            ("terminal", "终端"),
                        ],
                        max_length=50,
                    ),
                ),
                ("illustrator", models.CharField(default="", max_length=50)),
                ("implemented_at", models.DateField()),
                ("acquisition", models.JSONField(default=list)),
                ("description", models.TextField(default="")),
                ("illustration_1", models.TextField(default="")),
                ("illustration_2", models.TextField(default="")),
                (
                    "core_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inner_marks",
                        to="skill.passiveskill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(default="")),
                ("level_max_addition", models.TextField(default="")),
                (
                    "inner_mark",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traits",
                        to="inner_mark.innermark",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TraitLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField()),
                ("values", models.JSONField()),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="inner_mark.trait",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InnerMarkRegularSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inner_mark",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inner_mark.innermark",
                    ),
                ),
                (
                    "regular_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skill.passiveskill",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="innermark",
            name="regular_skills",
            field=models.ManyToManyField(
                through="inner_mark.InnerMarkRegularSkill", to="skill.passiveskill"
            ),
        ),
        migrations.CreateModel(
            name="EtchingStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField()),
                ("health", models.IntegerField()),
                ("defence", models.IntegerField()),
                ("attack", models.IntegerField()),
                ("mastery", models.IntegerField()),
                ("terminal", models.IntegerField()),
                (
                    "inner_mark",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etching_stats",
                        to="inner_mark.innermark",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CrossingStatLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField()),
                ("value", models.FloatField()),
                (
                    "crossing_stat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="inner_mark.crossingstat",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="crossingstat",
            name="inner_mark",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crossing_stats",
                to="inner_mark.innermark",
            ),
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("type", models.CharField(default="", max_length=50)),
                ("condition", models.CharField(default="", max_length=50)),
                ("description", models.TextField(default="")),
                ("detail", models.TextField(default="")),
                (
                    "inner_mark",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="inner_mark.innermark",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Awaken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phase_number", models.IntegerField()),
                ("choice_number", models.IntegerField()),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("health", "体质"),
                            ("defence", "防御"),
                            ("attack", "攻击"),
                            ("mastery", "专精"),
                            ("terminal", "终端"),
                            ("skill_point", "技能点"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.JSONField(default=list)),
                (
                    "inner_mark",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awakens",
                        to="inner_mark.innermark",
                    ),
                ),
            ],
        ),
    ]
